### ISSUE TITLE
[Bug] Krest tokens display issue

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#999] opened 2023-08-09 12:12 UTC
**Describe the bug**
KREST tokens do not show up on extension
Multiple users have reported having tokens but cannot view it in our wallet.

**Comment by 0xKheops** [comment] 2023-08-14 01:38
Same issue (and workaround) as #804 
Problem persists through browser restart, but goes away after toggling on or off the testnets.
Seems to be related to either websocket library or chain (data or connector) libraries
this bug might be best suited for @alecdwm

**Comment by chidg** [comment] 2023-11-03 02:58
@alecdwm any update on this? can it be closed?

**Comment by alecdwm** [comment] 2023-11-03 03:00
Not yet, we still don't have a reliable way to reproduce this one

**Comment by alecdwm** [comment] 2023-11-06 00:04
Actually this issue can be closed as a duplicate of https://github.com/TalismanSociety/talisman/issues/804, which is where I'm tracking some very strange and hard to reproduce behaviour Kheops and I noticed.

**Closed as not planned by alecdwm** 2023-11-06 00:04 UTC
Labels: P2 - medium, bug
