### ISSUE TITLE
Get Chaindata off  Squid to Cloudflare

### ISSUE THREAD

**Issue by 0byt** [TalismanSociety/talisman#984] opened 2023-08-02 14:13 UTC

**Comment by alecdwm** [comment] 2023-09-18 01:50
Duplicate of https://github.com/TalismanSociety/talisman/issues/1076

**Comment by 0xKheops** [comment] 2023-10-12 07:09
@alecdwm should we yeet this issue ?

**Comment by alecdwm** [comment] 2023-11-13 01:33
@0xKheops yeah! Closing as duplicate (of https://github.com/TalismanSociety/talisman/issues/1076)

**Closed as completed by alecdwm** 2023-11-13 01:33 UTC
